### ISSUE TITLE
Error Entity

### ISSUE THREAD

**Issue by pes001** [MislavMandaric/home-assistant-vaillant-vsmart#254] opened 2023-02-21 13:53 UTC
Hello, is it possible to add an entity that can report errors that Vaillant app reports (Boiler Error). For example when there is a little pressure in the water system, app shows red strip and notifies on the phone. I'd like to stop some HA automations that are related to boiler when it is in error or send a notificatoin via HA.
I would highly appreciate if would be added.
Thanks, Petr

**Comment by MislavMandaric** [comment] 2024-06-27 18:46
Duplicate of #215.

**Closed by MislavMandaric** 2024-06-27 18:46 UTC
