### ISSUE TITLE
Show actual DHW temp read from tank NTC

### ISSUE THREAD

**Issue by 21Development** [MislavMandaric/home-assistant-vaillant-vsmart#263] opened 2023-07-24 10:25 UTC
On a previous Vaillant controller (VRT 392) I could see the temperature of the DHW tank, as read by the NTC connected to VR65 and DHW tank. The vSmart doesn't appear to show this in the app and is greatly missed.

I see there's been a DHW Temperature number added which shows the set temp, it would be great to be able to see the actual tank temp as read by the NTC. As the vSmart uses the same VR65 and NTC, I'm hoping this data could still be read?

We used this previously to check how hot the water was and if a boost was required before use and is one of the really annoying missing features from the vSmart app vs the Vaillant one. Is this available on the API? Could it be exposed to HA?

**Comment by MislavMandaric** [comment] 2024-06-27 18:52
Check out #269. It should be possible to get this info, but I don't see this in the API response for my particular boiler, so I can't implement this myself.

If someone can help out with this, I'd gladly accept a PR.

I'll close this as a duplicate of #269, lets use that one to track this feature.

**Closed by MislavMandaric** 2024-06-27 18:52 UTC
